- name: install and remove the packeges
  hosts: frontend
  become: yes
  tasks:
    - name: remove nginx
      ansible.builtin.package:
        name: nginx
        state: absent
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes