- name: data types usage
  hosts: frontend
  vars: 
    course: "devops with aws"
    duration: 120
    tools:
    - linux
    - shell
    - aws
    concepts:
      cloud: aws
      cm: ansible
  tasks: 
    - name: data type
      ansible.builtin.debug:
      msg: "{{ course }}, {{ duration }}, {{ tools }}, {{ concepts }}"