- name: install and uninstall using loops
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: check the loop
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: "nginx", state: "absent" }
        - { name: "zip", state: "present" }
        - { name: "mysql", state: "latest" } 