- name: error handeling
  hosts: local
  connection: local
  tasks:
    - name: error equal to true
      ansible.builtin.command: id roboshob
      register: temp
      ignore_errors: true
    - name: printing the message
      ansible.builtin.debug:
        msg: "{{ temp }}"